- name: Create Dashboard File
  ansible.builtin.template:
    src: dashboard.json
    dest: /tmp/dashboard.json

- name: Add Grafana dashboard
  community.grafana.grafana_dashboard:
    grafana_url: http://172.31.41.253:3000
    #grafana_api_key: "{{ lookup('amazon.aws.aws_ssm', 'grafana.api_key', region='us-east-1' ) }}"
    grafana_api_key: "glsa_o10RUxuf3xn52bmj8hEIJLawjQqf89aO_51d5761b"
    state: present
    commit_message: Updated by ansible
    overwrite: yes
    path: /tmp/dashboard.json


